version: "3"

services:
    HostA:
        image: handsonsecurity/seed-ubuntu:large
        container_name: host-A-10.0.32.5
        tty: true
        cap_add:
                - ALL
        networks:
            net-private-1:
                ipv4_address: 10.0.32.5
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.32.12  &&
                      ip addr del 10.0.32.5/25 dev eth0 &&
                      ip addr add 10.0.32.5/24 dev eth0 &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "

    HostB:
        image: handsonsecurity/seed-ubuntu:large
        container_name: host-B-10.0.32.6
        tty: true
        cap_add:
                - ALL
        networks:
            net-private-1:
                ipv4_address: 10.0.32.6
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.32.12  &&
                      ip addr del 10.0.32.6/25 dev eth0 &&
                      ip addr add 10.0.32.6/24 dev eth0 &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "

    VPN_Client:
        image: handsonsecurity/seed-ubuntu:large
        container_name: vpn-client-10.0.7.12
        tty: true
        cap_add:
                - ALL
        devices:
                - "/dev/net/tun:/dev/net/tun"
        sysctls:
                - net.ipv4.ip_forward=1
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.0.7.0:
                ipv4_address: 10.0.7.12
            net-private-1:
                ipv4_address: 10.0.32.12
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.7.1 &&
                      tail -f /dev/null
                 "

    HostC:
        image: handsonsecurity/seed-ubuntu:large
        container_name: host-C-10.0.32.133
        tty: true
        cap_add:
                - ALL
        networks:
            net-private-2:
                ipv4_address: 10.0.32.133
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.32.211  &&
                      ip addr del 10.0.32.133/25 dev eth0 &&
                      ip addr add 10.0.32.133/24 dev eth0 &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "
                  
    HostD:
        image: handsonsecurity/seed-ubuntu:large
        container_name: host-D-10.0.32.134
        tty: true
        cap_add:
                - ALL
        networks:
            net-private-2:
                ipv4_address: 10.0.32.134
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.32.211  &&
                      ip addr del 10.0.32.134/25 dev eth0 &&
                      ip addr add 10.0.32.134/24 dev eth0 &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "

    VPN-Server:
        image: handsonsecurity/seed-ubuntu:large
        container_name: vpn-server-10.0.7.11
        tty: true
        cap_add:
                - ALL
        devices:
                - "/dev/net/tun:/dev/net/tun"
        sysctls:
                - net.ipv4.ip_forward=1
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.0.7.0:
                ipv4_address: 10.0.7.11
            net-private-2:
                ipv4_address: 10.0.32.211
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.7.1 &&
                      tail -f /dev/null
                 "

networks:
    net-private-1:
        name: net-private-1
        ipam:
            config:
                - subnet: 10.0.32.0/25

    net-private-2:
        name: net-private-2
        ipam:
            config:
                - subnet: 10.0.32.128/25

    net-10.0.7.0:
        name: net-10.0.7.0
        ipam:
            config:
                - subnet: 10.0.7.0/24

