version: "3"

services:
    HostA:
        image: handsonsecurity/seed-ubuntu:large
        container_name: host-10.0.6.5
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.0.6.0:
                ipv4_address: 10.0.6.5
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.6.12  &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "

    HostB:
        image: handsonsecurity/seed-ubuntu:large
        container_name: host-10.0.6.6
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.0.6.0:
                ipv4_address: 10.0.6.6
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.6.12  &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "

    VPN_Client:
        image: handsonsecurity/seed-ubuntu:large
        container_name: client-10.0.7.12
        tty: true
        cap_add:
                - ALL
        devices:
                - "/dev/net/tun:/dev/net/tun"
        sysctls:
                - net.ipv4.ip_forward=1
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.0.7.0:
                ipv4_address: 10.0.7.12
            net-10.0.6.0:
                ipv4_address: 10.0.6.12
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.7.1 &&
                      tail -f /dev/null
                 "

    Host1:
        image: handsonsecurity/seed-ubuntu:large
        container_name: host-10.0.8.5
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.0.8.0:
                ipv4_address: 10.0.8.5
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.8.11  &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "
                  
    Host2:
        image: handsonsecurity/seed-ubuntu:large
        container_name: host-10.0.8.6
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.0.8.0:
                ipv4_address: 10.0.8.6
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.8.11  &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "

    Router:
        image: handsonsecurity/seed-ubuntu:large
        container_name: server-router-10.0.7.11
        tty: true
        cap_add:
                - ALL
        devices:
                - "/dev/net/tun:/dev/net/tun"
        sysctls:
                - net.ipv4.ip_forward=1
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.0.7.0:
                ipv4_address: 10.0.7.11
            net-10.0.8.0:
                ipv4_address: 10.0.8.11
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.0.7.1 &&
                      tail -f /dev/null
                 "

networks:
    net-10.0.6.0:
        name: net-10.0.6.0
        ipam:
            config:
                - subnet: 10.0.6.0/24
    net-10.0.8.0:
        name: net-10.0.8.0
        ipam:
            config:
                - subnet: 10.0.8.0/24

    net-10.0.7.0:
        name: net-10.0.7.0
        ipam:
            config:
                - subnet: 10.0.7.0/24

